### ISSUE TITLE
`#increaseLiquidity` return arguments are not set

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-v3-periphery-optimism#1]
https://github.com/Uniswap/uniswap-v3-periphery-optimism/blob/34eb2a74a1a98ef8e5da0c64d950d72a13e7cadd/contracts/NonfungiblePositionManager.sol#L121-L137

**Comment by NoahZinsmeister** [comment]
closed in d475b7ba012e3a29a5e5858b8e2984e723f1a3a0
